--CREATE TABLE IF NOT EXISTS users (
--    id BIGSERIAL PRIMARY KEY,
--    name VARCHAR(255),
--    email VARCHAR(255)
--);
--
--
--
--CREATE TABLE IF NOT EXISTS users (
--    id BIGINT AUTO_INCREMENT PRIMARY KEY,
--    NAME VARCHAR(255),
--    email VARCHAR(255)
--);

CREATE TABLE IF NOT EXISTS technologies (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(255),
    DESCRIPTION VARCHAR(255)
);